version: "3.9"

services:
  email-service:
    build: .
    container_name: email_service
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - email_db
      - redis

  email_db:
    image: postgres:15
    container_name: email_db
    environment:
      POSTGRES_DB: emaildb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - email_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis_email
    ports:
      - "6382:6379"

volumes:
  email_data:
