version: '3.8'

services:
  auth:
    build: .
    container_name: auth_service
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: auth_redis
    restart: always
    ports:
      - "6380:6379"

volumes:
  pgdata:
